# Generated by Django 3.2.13 on 2022-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('initiate_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Experiment Log',
                'verbose_name_plural': 'Experiment Logs',
            },
        ),
    ]
