# Generated by Django 3.2.13 on 2022-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentlog',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
