# Generated by Django 3.2.13 on 2022-04-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_experimentlog_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentlog',
            name='agent_balance_change',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='experimentlog',
            name='attacker_balance_change',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=28),
        ),
    ]
