# Generated by Django 3.2.13 on 2022-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_url', models.CharField(max_length=1024)),
                ('chain_id', models.PositiveIntegerField()),
                ('account_address', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[['success', 'Success'], ['reverted', 'Reverted'], ['pending', 'Pending'], ['cancelled', 'Cancelled'], ['dropped', 'Dropped']], default='pending', max_length=256)),
                ('gas_speed', models.CharField(choices=[['slow', 'Slow'], ['average', 'Average'], ['fast', 'Fast']], max_length=256)),
                ('data', models.JSONField()),
                ('hash', models.CharField(max_length=1024)),
                ('receipt', models.JSONField(null=True)),
                ('last_sent', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
