# Generated by Django 3.2.13 on 2022-04-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
        ('tx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtx',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='dbtx',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='primary.experimentlog'),
        ),
    ]
