# Generated by Django 3.2.13 on 2022-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx', '0002_auto_20220428_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtx',
            name='nonce',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
